import { BookTicketResponseModel, BusSeatInfoModel } from '../models/book-ticket.model';

export const mockResponse: BookTicketResponseModel = {
	type: "Bus",
	seats: [
   {
      "seatNo":1,
      "status":"available"
   },
   {
      "seatNo":2,
      "status":"available"
   },
   {
      "seatNo":3,
      "status":"available"
   },
   {
      "seatNo":4,
      "status":"available"
   },
   {
      "seatNo":5,
      "status":"available"
   },
   {
      "seatNo":6,
      "status":"available"
   },
   {
      "seatNo":7,
      "status":"available"
   },
   {
      "seatNo":8,
      "status":"available"
   },
   {
      "seatNo":9,
      "status":"available"
   },
   {
      "seatNo":10,
      "status":"available"
   },
   {
      "seatNo":11,
      "status":"available"
   },
   {
      "seatNo":12,
      "status":"available"
   },
   {
      "seatNo":13,
      "status":"available"
   },
   {
      "seatNo":14,
      "status":"available"
   },
   {
      "seatNo":15,
      "status":"available"
   },
   {
      "seatNo":16,
      "status":"available"
   },
   {
      "seatNo":17,
      "status":"available"
   },
   {
      "seatNo":18,
      "status":"available"
   },
   {
      "seatNo":19,
      "status":"available"
   },
   {
      "seatNo":20,
      "status":"available"
   },
   {
      "seatNo":21,
      "status":"available"
   },
   {
      "seatNo":22,
      "status":"available"
   },
   {
      "seatNo":23,
      "status":"available"
   },
   {
      "seatNo":24,
      "status":"available"
   },
   {
      "seatNo":25,
      "status":"available"
   },
   {
      "seatNo":26,
      "status":"available"
   },
   {
      "seatNo":27,
      "status":"available"
   },
   {
      "seatNo":28,
      "status":"available"
   },
   {
      "seatNo":29,
      "status":"available"
   },
   {
      "seatNo":30,
      "status":"available"
   },
   {
      "seatNo":31,
      "status":"available"
   },
   {
      "seatNo":32,
      "status":"available"
   },
   {
      "seatNo":33,
      "status":"available"
   },
   {
      "seatNo":34,
      "status":"available"
   },
   {
      "seatNo":35,
      "status":"available"
   },
   {
      "seatNo":36,
      "status":"available"
   },
   {
      "seatNo":37,
      "status":"available"
   },
   {
      "seatNo":38,
      "status":"available"
   },
   {
      "seatNo":39,
      "status":"available"
   },
   {
      "seatNo":40,
      "status":"available"
   },
   {
      "seatNo":41,
      "status":"available"
   },
   {
      "seatNo":42,
      "status":"available"
   },
   {
      "seatNo":43,
      "status":"available"
   },
   {
      "seatNo":44,
      "status":"available"
   },
   {
      "seatNo":45,
      "status":"available"
   },
   {
      "seatNo":46,
      "status":"available"
   },
   {
      "seatNo":47,
      "status":"available"
   },
   {
      "seatNo":48,
      "status":"available"
   },
   {
      "seatNo":49,
      "status":"available"
   },
   {
      "seatNo":50,
      "status":"available"
   },
   {
      "seatNo":51,
      "status":"available"
   },
   {
      "seatNo":52,
      "status":"available"
   },
   {
      "seatNo":53,
      "status":"available"
   },
   {
      "seatNo":54,
      "status":"available"
   },
   {
      "seatNo":55,
      "status":"available"
   },
   {
      "seatNo":56,
      "status":"available"
   },
   {
      "seatNo":57,
      "status":"available"
   },
   {
      "seatNo":58,
      "status":"available"
   },
   {
      "seatNo":59,
      "status":"available"
   },
   {
      "seatNo":60,
      "status":"available"
   },
   {
      "seatNo":61,
      "status":"available"
   },
   {
      "seatNo":62,
      "status":"available"
   },
   {
      "seatNo":63,
      "status":"available"
   },
   {
      "seatNo":64,
      "status":"available"
   },
   {
      "seatNo":65,
      "status":"available"
   },
   {
      "seatNo":66,
      "status":"available"
   },
   {
      "seatNo":67,
      "status":"available"
   },
   {
      "seatNo":68,
      "status":"available"
   },
   {
      "seatNo":69,
      "status":"available"
   },
   {
      "seatNo":70,
      "status":"available"
   },
   {
      "seatNo":71,
      "status":"available"
   },
   {
      "seatNo":72,
      "status":"available"
   },
   {
      "seatNo":73,
      "status":"available"
   },
   {
      "seatNo":74,
      "status":"available"
   },
   {
      "seatNo":75,
      "status":"available"
   },
   {
      "seatNo":76,
      "status":"available"
   },
   {
      "seatNo":77,
      "status":"available"
   },
   {
      "seatNo":78,
      "status":"available"
   },
   {
      "seatNo":79,
      "status":"available"
   },
   {
      "seatNo":80,
      "status":"available"
   }
]
};
